# Generated by Django 5.1 on 2024-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('comuna', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('pregunta1', models.BooleanField()),
                ('pregunta2', models.BooleanField()),
                ('pregunta3', models.BooleanField()),
            ],
        ),
    ]
